// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb25maWcucHJvdG8SBkNvbmZpZyKmAgoFZXF1aXASJQoHcmVjb3JkcxgB",
            "IAMoCzIULkNvbmZpZy5lcXVpcC5SZWNvcmQSDwoHdmVyc2lvbhgCIAEoAxrk",
            "AQoGUmVjb3JkEgoKAmlkGAEgASgFEgwKBG5hbWUYAiABKAkSFQoNbG9jYXRp",
            "b25fdHlwZRgDIAEoBRIPCgdxdWFsaXR5GAQgASgFEgwKBHN0YXIYBSABKAUS",
            "FQoNcHJvcGVydHlfdHlwZRgGIAMoBRIUCgxwcm9wZXJ0eV9udW0YByADKAUS",
            "EgoKZm9yd2FyZF9pZBgIIAEoBRIVCg1jb21wb3NlX21vbmV5GAkgASgFEhIK",
            "CmltYWdlX25hbWUYCiABKAkSDwoHc3VpdF9pZBgLIAEoBRINCgVwcmljZRgM",
            "IAEoBUIRWgZjb25maWeqAgZDb25maWdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.equip), global::Config.equip.Parser, new[]{ "Records", "Version" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Config.equip.Types.Record), global::Config.equip.Types.Record.Parser, new[]{ "Id", "Name", "LocationType", "Quality", "Star", "PropertyType", "PropertyNum", "ForwardId", "ComposeMoney", "ImageName", "SuitId", "Price" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class equip : pb::IMessage<equip> {
    private static readonly pb::MessageParser<equip> _parser = new pb::MessageParser<equip>(() => new equip());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<equip> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public equip() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public equip(equip other) : this() {
      records_ = other.records_.Clone();
      version_ = other.version_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public equip Clone() {
      return new equip(this);
    }

    /// <summary>Field number for the "records" field.</summary>
    public const int RecordsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Config.equip.Types.Record> _repeated_records_codec
        = pb::FieldCodec.ForMessage(10, global::Config.equip.Types.Record.Parser);
    private readonly pbc::RepeatedField<global::Config.equip.Types.Record> records_ = new pbc::RepeatedField<global::Config.equip.Types.Record>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Config.equip.Types.Record> Records {
      get { return records_; }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private long version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as equip);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(equip other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!records_.Equals(other.records_)) return false;
      if (Version != other.Version) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= records_.GetHashCode();
      if (Version != 0L) hash ^= Version.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      records_.WriteTo(output, _repeated_records_codec);
      if (Version != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Version);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += records_.CalculateSize(_repeated_records_codec);
      if (Version != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Version);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(equip other) {
      if (other == null) {
        return;
      }
      records_.Add(other.records_);
      if (other.Version != 0L) {
        Version = other.Version;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            records_.AddEntriesFrom(input, _repeated_records_codec);
            break;
          }
          case 16: {
            Version = input.ReadInt64();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the equip message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Record : pb::IMessage<Record> {
        private static readonly pb::MessageParser<Record> _parser = new pb::MessageParser<Record>(() => new Record());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Record> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Config.equip.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Record() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Record(Record other) : this() {
          id_ = other.id_;
          name_ = other.name_;
          locationType_ = other.locationType_;
          quality_ = other.quality_;
          star_ = other.star_;
          propertyType_ = other.propertyType_.Clone();
          propertyNum_ = other.propertyNum_.Clone();
          forwardId_ = other.forwardId_;
          composeMoney_ = other.composeMoney_;
          imageName_ = other.imageName_;
          suitId_ = other.suitId_;
          price_ = other.price_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Record Clone() {
          return new Record(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private int id_;
        /// <summary>
        /// ID
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Id {
          get { return id_; }
          set {
            id_ = value;
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 2;
        private string name_ = "";
        /// <summary>
        /// 名称
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "location_type" field.</summary>
        public const int LocationTypeFieldNumber = 3;
        private int locationType_;
        /// <summary>
        /// 位置类型
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int LocationType {
          get { return locationType_; }
          set {
            locationType_ = value;
          }
        }

        /// <summary>Field number for the "quality" field.</summary>
        public const int QualityFieldNumber = 4;
        private int quality_;
        /// <summary>
        /// 品质
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Quality {
          get { return quality_; }
          set {
            quality_ = value;
          }
        }

        /// <summary>Field number for the "star" field.</summary>
        public const int StarFieldNumber = 5;
        private int star_;
        /// <summary>
        /// 星级
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Star {
          get { return star_; }
          set {
            star_ = value;
          }
        }

        /// <summary>Field number for the "property_type" field.</summary>
        public const int PropertyTypeFieldNumber = 6;
        private static readonly pb::FieldCodec<int> _repeated_propertyType_codec
            = pb::FieldCodec.ForInt32(50);
        private readonly pbc::RepeatedField<int> propertyType_ = new pbc::RepeatedField<int>();
        /// <summary>
        /// 属性类型
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<int> PropertyType {
          get { return propertyType_; }
        }

        /// <summary>Field number for the "property_num" field.</summary>
        public const int PropertyNumFieldNumber = 7;
        private static readonly pb::FieldCodec<int> _repeated_propertyNum_codec
            = pb::FieldCodec.ForInt32(58);
        private readonly pbc::RepeatedField<int> propertyNum_ = new pbc::RepeatedField<int>();
        /// <summary>
        /// 属性值
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<int> PropertyNum {
          get { return propertyNum_; }
        }

        /// <summary>Field number for the "forward_id" field.</summary>
        public const int ForwardIdFieldNumber = 8;
        private int forwardId_;
        /// <summary>
        /// 前置ID
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int ForwardId {
          get { return forwardId_; }
          set {
            forwardId_ = value;
          }
        }

        /// <summary>Field number for the "compose_money" field.</summary>
        public const int ComposeMoneyFieldNumber = 9;
        private int composeMoney_;
        /// <summary>
        /// 合成消耗金币
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int ComposeMoney {
          get { return composeMoney_; }
          set {
            composeMoney_ = value;
          }
        }

        /// <summary>Field number for the "image_name" field.</summary>
        public const int ImageNameFieldNumber = 10;
        private string imageName_ = "";
        /// <summary>
        /// 图标
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ImageName {
          get { return imageName_; }
          set {
            imageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "suit_id" field.</summary>
        public const int SuitIdFieldNumber = 11;
        private int suitId_;
        /// <summary>
        /// 套装ID
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int SuitId {
          get { return suitId_; }
          set {
            suitId_ = value;
          }
        }

        /// <summary>Field number for the "price" field.</summary>
        public const int PriceFieldNumber = 12;
        private int price_;
        /// <summary>
        /// 出售价格
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Price {
          get { return price_; }
          set {
            price_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Record);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Record other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if (Name != other.Name) return false;
          if (LocationType != other.LocationType) return false;
          if (Quality != other.Quality) return false;
          if (Star != other.Star) return false;
          if(!propertyType_.Equals(other.propertyType_)) return false;
          if(!propertyNum_.Equals(other.propertyNum_)) return false;
          if (ForwardId != other.ForwardId) return false;
          if (ComposeMoney != other.ComposeMoney) return false;
          if (ImageName != other.ImageName) return false;
          if (SuitId != other.SuitId) return false;
          if (Price != other.Price) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Id != 0) hash ^= Id.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (LocationType != 0) hash ^= LocationType.GetHashCode();
          if (Quality != 0) hash ^= Quality.GetHashCode();
          if (Star != 0) hash ^= Star.GetHashCode();
          hash ^= propertyType_.GetHashCode();
          hash ^= propertyNum_.GetHashCode();
          if (ForwardId != 0) hash ^= ForwardId.GetHashCode();
          if (ComposeMoney != 0) hash ^= ComposeMoney.GetHashCode();
          if (ImageName.Length != 0) hash ^= ImageName.GetHashCode();
          if (SuitId != 0) hash ^= SuitId.GetHashCode();
          if (Price != 0) hash ^= Price.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Id != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Id);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Name);
          }
          if (LocationType != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(LocationType);
          }
          if (Quality != 0) {
            output.WriteRawTag(32);
            output.WriteInt32(Quality);
          }
          if (Star != 0) {
            output.WriteRawTag(40);
            output.WriteInt32(Star);
          }
          propertyType_.WriteTo(output, _repeated_propertyType_codec);
          propertyNum_.WriteTo(output, _repeated_propertyNum_codec);
          if (ForwardId != 0) {
            output.WriteRawTag(64);
            output.WriteInt32(ForwardId);
          }
          if (ComposeMoney != 0) {
            output.WriteRawTag(72);
            output.WriteInt32(ComposeMoney);
          }
          if (ImageName.Length != 0) {
            output.WriteRawTag(82);
            output.WriteString(ImageName);
          }
          if (SuitId != 0) {
            output.WriteRawTag(88);
            output.WriteInt32(SuitId);
          }
          if (Price != 0) {
            output.WriteRawTag(96);
            output.WriteInt32(Price);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Id != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (LocationType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(LocationType);
          }
          if (Quality != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quality);
          }
          if (Star != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Star);
          }
          size += propertyType_.CalculateSize(_repeated_propertyType_codec);
          size += propertyNum_.CalculateSize(_repeated_propertyNum_codec);
          if (ForwardId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ForwardId);
          }
          if (ComposeMoney != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ComposeMoney);
          }
          if (ImageName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageName);
          }
          if (SuitId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(SuitId);
          }
          if (Price != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Record other) {
          if (other == null) {
            return;
          }
          if (other.Id != 0) {
            Id = other.Id;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.LocationType != 0) {
            LocationType = other.LocationType;
          }
          if (other.Quality != 0) {
            Quality = other.Quality;
          }
          if (other.Star != 0) {
            Star = other.Star;
          }
          propertyType_.Add(other.propertyType_);
          propertyNum_.Add(other.propertyNum_);
          if (other.ForwardId != 0) {
            ForwardId = other.ForwardId;
          }
          if (other.ComposeMoney != 0) {
            ComposeMoney = other.ComposeMoney;
          }
          if (other.ImageName.Length != 0) {
            ImageName = other.ImageName;
          }
          if (other.SuitId != 0) {
            SuitId = other.SuitId;
          }
          if (other.Price != 0) {
            Price = other.Price;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Id = input.ReadInt32();
                break;
              }
              case 18: {
                Name = input.ReadString();
                break;
              }
              case 24: {
                LocationType = input.ReadInt32();
                break;
              }
              case 32: {
                Quality = input.ReadInt32();
                break;
              }
              case 40: {
                Star = input.ReadInt32();
                break;
              }
              case 50:
              case 48: {
                propertyType_.AddEntriesFrom(input, _repeated_propertyType_codec);
                break;
              }
              case 58:
              case 56: {
                propertyNum_.AddEntriesFrom(input, _repeated_propertyNum_codec);
                break;
              }
              case 64: {
                ForwardId = input.ReadInt32();
                break;
              }
              case 72: {
                ComposeMoney = input.ReadInt32();
                break;
              }
              case 82: {
                ImageName = input.ReadString();
                break;
              }
              case 88: {
                SuitId = input.ReadInt32();
                break;
              }
              case 96: {
                Price = input.ReadInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
